"""Add notes and alert_time to tasks

Revision ID: c24962846aac
Revises: 
Create Date: 2025-09-16 22:17:53.867357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24962846aac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('alert_time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'telegram_users', 'profiles', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_users', type_='foreignkey')
    op.drop_column('tasks', 'alert_time')
    op.drop_column('tasks', 'notes')
    # ### end Alembic commands ###
