"""Add Google OAuth fields to User model

Revision ID: f883e0c92c69
Revises: 155dbc03c44f
Create Date: 2025-09-24 17:38:39.136481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f883e0c92c69'
down_revision: Union[str, None] = '155dbc03c44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('state_data', sa.JSON(), nullable=True))
    op.add_column('profiles', sa.Column('google_id', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('google_refresh_token', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('google_access_token', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('google_token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('profiles', sa.Column('google_contacts_synced_at', sa.DateTime(), nullable=True))
    op.add_column('profiles', sa.Column('google_calendar_synced_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'profiles', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'google_calendar_synced_at')
    op.drop_column('profiles', 'google_contacts_synced_at')
    op.drop_column('profiles', 'google_token_expires_at')
    op.drop_column('profiles', 'google_access_token')
    op.drop_column('profiles', 'google_refresh_token')
    op.drop_column('profiles', 'google_id')
    op.drop_column('profiles', 'state_data')
    # ### end Alembic commands ###
