version: 1.0
runtime: docker
run:
  runtime-version: latest
  command: python main.py
  network:
    port: 8080
    env: PORT
  env:
    - name: ENVIRONMENT
      value: production
    - name: PORT
      value: "8080"
    - name: DATABASE_URL
      value: "postgresql://postgres:123456@localhost:5432/neo_networker"