"""add_state_data_to_user_model

Revision ID: 155dbc03c44f
Revises: ce2d0499f3b1
Create Date: 2025-09-23 00:46:53.868862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155dbc03c44f'
down_revision: Union[str, None] = 'ce2d0499f3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
