"""remove_unique_constraint_from_task_id

Revision ID: 9d51574f9aea
Revises: c24962846aac
Create Date: 2025-09-16 23:17:14.769618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d51574f9aea'
down_revision: Union[str, None] = 'c24962846aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_task_id_key', 'tasks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tasks_task_id_key', 'tasks', ['task_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
