"""Add WhatsApp support to User model

Revision ID: ce2d0499f3b1
Revises: 59d777f498bb
Create Date: 2025-09-22 14:32:07.063867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2d0499f3b1'
down_revision: Union[str, None] = '59d777f498bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('whatsapp_phone', sa.String(length=20), nullable=True))
    op.add_column('profiles', sa.Column('preferred_messaging_platform', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'profiles', ['whatsapp_phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'preferred_messaging_platform')
    op.drop_column('profiles', 'whatsapp_phone')
    # ### end Alembic commands ###
