"""add google_sync to events

Revision ID: add_google_sync_to_events
Revises: a62be9245d08
Create Date: 2025-01-08 20:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_google_sync_to_events'
down_revision = 'a62be9245d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('google_sync', sa.Boolean(), nullable=True, default=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'google_sync')
    # ### end Alembic commands ###
