-- Insert mock data for people table
INSERT INTO public.people (full_name, company, career_history, professional_specialties, hashtags, notes) VALUES 
('Sarah Johnson', 'Sequoia Capital', 'VP at Google, Senior PM at Meta, Started 2 companies', ARRAY['Product Management', 'AI/ML', 'Growth'], ARRAY['product', 'ai', 'growth', 'saas'], 'Former founder with strong product background'),
('Michael Chen', 'Andreessen Horowitz', 'CTO at Stripe, Engineering Lead at Uber', ARRAY['Engineering', 'Fintech', 'Blockchain'], ARRAY['fintech', 'blockchain', 'engineering', 'crypto'], 'Technical leader with fintech expertise'),
('Emily Rodriguez', 'Kleiner Perkins', 'Head of Marketing at Airbnb, CMO at 3 startups', ARRAY['Marketing', 'Brand Strategy', 'Consumer Tech'], ARRAY['marketing', 'branding', 'consumer', 'growth'], 'Consumer marketing expert'),
('David Kim', 'Lightspeed Venture Partners', 'Serial entrepreneur, 3 exits, Former McKinsey consultant', ARRAY['Strategy', 'Healthcare Tech', 'B2B SaaS'], ARRAY['healthcare', 'b2b', 'strategy', 'exits'], 'Healthcare tech entrepreneur'),
('Jessica Taylor', 'Accel Partners', 'Head of Sales at Salesforce, VP Sales at 2 unicorns', ARRAY['Sales', 'Enterprise Software', 'Go-to-Market'], ARRAY['sales', 'enterprise', 'saas', 'gtm'], 'Enterprise sales leader'),
('Alex Thompson', 'Benchmark Capital', 'Senior Engineer at Google, Technical Co-founder', ARRAY['Software Engineering', 'Developer Tools', 'Open Source'], ARRAY['engineering', 'devtools', 'opensource', 'infrastructure'], 'Open source contributor and technical founder'),
('Maria Garcia', 'First Round Capital', 'CPO at Spotify, Product Lead at Netflix', ARRAY['Product Management', 'Media Tech', 'Consumer Products'], ARRAY['product', 'media', 'streaming', 'consumer'], 'Consumer product expert in media/entertainment'),
('Robert Wilson', 'General Catalyst', 'CFO at 2 unicorns, Former Goldman Sachs VP', ARRAY['Finance', 'Investment Banking', 'Corporate Development'], ARRAY['finance', 'banking', 'corpdev', 'ipo'], 'Financial operations and M&A expert'),
('Lisa Park', 'GV (Google Ventures)', 'Design Director at IDEO, Head of Design at 3 startups', ARRAY['Product Design', 'User Experience', 'Design Systems'], ARRAY['design', 'ux', 'ui', 'designsystems'], 'Design systems and UX expert'),
('James Anderson', 'NEA', 'VP Engineering at Tesla, CTO at autonomous vehicle startup', ARRAY['Automotive Tech', 'AI/ML', 'Hardware'], ARRAY['automotive', 'ai', 'hardware', 'autonomous'], 'Autonomous vehicle technology expert'),
('Amanda Lee', 'Insight Partners', 'Head of Data Science at Uber, ML Engineer at Facebook', ARRAY['Data Science', 'Machine Learning', 'Analytics'], ARRAY['datascience', 'ml', 'analytics', 'ai'], 'Data science and ML infrastructure expert'),
('Christopher Brown', 'Tiger Global Management', 'CEO of 2 startups, Former Bain consultant', ARRAY['Business Strategy', 'E-commerce', 'International Expansion'], ARRAY['strategy', 'ecommerce', 'international', 'consulting'], 'International business development expert'),
('Rachel Davis', 'Founders Fund', 'VP of Engineering at SpaceX, Aerospace engineer at Boeing', ARRAY['Aerospace Engineering', 'Deep Tech', 'Manufacturing'], ARRAY['aerospace', 'deeptech', 'manufacturing', 'space'], 'Deep tech and aerospace engineering expert'),
('Kevin Zhang', 'Greylock Partners', 'Head of Security at Coinbase, Cybersecurity expert', ARRAY['Cybersecurity', 'Blockchain', 'Risk Management'], ARRAY['security', 'blockchain', 'risk', 'fintech'], 'Cybersecurity and blockchain security expert'),
('Sophie Miller', 'Index Ventures', 'VP of People at Slack, HR Director at 4 startups', ARRAY['Human Resources', 'Talent Acquisition', 'Organizational Development'], ARRAY['hr', 'talent', 'culture', 'scaling'], 'People operations and talent expert');