// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufekkcirsznhrvqwwsyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmZWtrY2lyc3puaHJ2cXd3c3lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzk5NzksImV4cCI6MjA3Mjc1NTk3OX0.Rdtri53bOEK0V0R6IjRpCRy2Aiuz7RJTs_-IhUaegOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});