name: Deploy Neo Networker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install backend dependencies
      run: |
        cd backend
        pip install -r requirements.txt
    
    - name: Run basic tests
      env:
        DATABASE_URL: sqlite:///test.db
        JWT_SECRET_KEY: test-secret-key
        OPENAI_API_KEY: test-openai-key
        TELEGRAM_BOT_TOKEN: test-telegram-token
        WHATSAPP_ACCESS_TOKEN: test-whatsapp-token
        WHATSAPP_PHONE_NUMBER_ID: test-phone-id
        WHATSAPP_WEBHOOK_VERIFY_TOKEN: test-verify-token
      run: |
        python -m pytest tests/integration/test_basic.py -v
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Run frontend tests
      run: |
        cd frontend
        npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build backend Docker image
      run: |
        docker build -f docker/Dockerfile.backend -t neo-backend:${{ github.sha }} .
    
    - name: Build frontend Docker image
      run: |
        docker build -f docker/Dockerfile.frontend -t neo-frontend:${{ github.sha }} .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy to AWS App Runner
      run: |
        aws apprunner start-deployment \
          --service-arn ${{ secrets.APP_RUNNER_SERVICE_ARN }}
