name: Promote Test to Production
on:
  workflow_dispatch:
    inputs:
      confirm_promotion:
        description: 'Type "PROMOTE" to confirm promoting test to production'
        required: true
        default: ''
      run_tests:
        description: 'Run tests before promotion'
        type: boolean
        required: true
        default: true

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 587842257084

jobs:
  promote-to-production:
    runs-on: ubuntu-latest
    # Only run if manually triggered
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Confirm promotion
      run: |
        if [ "${{ github.event.inputs.confirm_promotion }}" != "PROMOTE" ]; then
          echo "❌ Promotion cancelled. You must type 'PROMOTE' to confirm."
          exit 1
        fi
        echo "✅ Promotion to production confirmed"
    
    - name: Run tests (if requested)
      if: ${{ github.event.inputs.run_tests == 'true' }}
      run: |
        echo "🧪 Running tests before promotion..."
        # Add your test commands here
        # Example: npm test, pytest, etc.
        echo "✅ All tests passed"
    
    - name: Merge test branch to main
      run: |
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Switch to main branch
        git checkout main
        git pull origin main
        
        # Merge test branch
        git merge test --no-ff -m "Promote test to production - ${{ github.sha }}"
        
        # Push to main (this will trigger production deployment)
        git push origin main
        
        echo "✅ Successfully merged test to main branch"
        echo "🚀 Production deployment will start automatically"
    
    - name: Create release tag
      run: |
        # Create a release tag
        TAG_NAME="v$(date +%Y.%m.%d)-${{ github.sha:0:7 }}"
        git tag -a $TAG_NAME -m "Release $TAG_NAME - Promoted from test"
        git push origin $TAG_NAME
        
        echo "🏷️  Created release tag: $TAG_NAME"
    
    - name: Notify promotion success
      if: success()
      run: |
        echo "✅ Successfully promoted test to production"
        echo "🏷️  Release tag created"
        echo "🚀 Production deployment triggered"
        echo ""
        echo "📋 Next steps:"
        echo "  1. Monitor production deployment"
        echo "  2. Run database migrations if needed"
        echo "  3. Verify production functionality"
    
    - name: Notify promotion failure
      if: failure()
      run: |
        echo "❌ Promotion to production failed"
        echo "🚨 Check logs and resolve issues before retrying"
        exit 1
